### ISSUE TITLE
Nerdfonts are no longer showing

### ISSUE THREAD

**Issue by Duponin** [andreyorst/powerline.kak#11]
## Problem description

Hi, thank you for your plugin.
Since I update powerline addon, it's not as fancy as before.

## Steps to reproduce

1. plug-update
2. start kakoune
3. see

## What should happen

A beautiful powerline should be showed

## What happens instead

A powerline without any Nerdfonts but with colors

## Environment information
Kakoune version: Kakoune v2019.01.20
OS version: Void Linux 4.19.48_1 (kernel)
`sh` executable version: zsh 5.7.1 (x86_64-unknown-linux-gnu)
*debug*: `/home/antonin/.config/kak/plugins/powerline.kak/rc/modules/bufname.kak:11:733: 'hook' no such hook: 'ModuleLoad'`

## Screenshots

The correct one:

![correct](https://user-images.githubusercontent.com/32687841/59952173-85e86900-947b-11e9-8375-5fd445832139.png)

The issued one (after update):

![issue](https://user-images.githubusercontent.com/32687841/59952182-93055800-947b-11e9-9250-43db937c7761.png)

**Comment by andreyorst** [comment]
#10

the last screenshot is default Kakoune modeline, not powerline
