### ISSUE TITLE
no such command: 'powerline-enable'

### ISSUE THREAD

**Issue by Luflosi** [andreyorst/powerline.kak#14]
When trying to use the latest master version a2b550c, the following error occurred:
```
plug.kak: Error occured while loading 'andreyorst/powerline.kak' plugin:        
          2:6: 'evaluate-commands' 27:2146: 'evaluate-commands' no such         
          command: 'powerline-enable'
```
I put
```
plug "andreyorst/powerline.kak" config %{
    powerline-enable
}
```
into my kakrc, as recommended in the README.
If I replace `powerline-enable` with `powerline-start`, everything seems to work fine. I think the documentation needs updating.

**Comment by andreyorst** [comment]
it seems I've forgot to change the beginning of documentation. Here's how it should be done: https://github.com/andreyorst/powerline.kak#example-configuration-using-plugkak
