### ISSUE TITLE
Git module doesn't display unless powerline disabled and re-enabled

### ISSUE THREAD

**Issue by johnisom** [andreyorst/powerline.kak#16]
## Problem description

When using the `git` module with powerline and starting a new kakoune session within a git reopsitory (`kak README.md`), the module doesn't appear on the powerline bar until powerline is disabled and then enabled (`:powerline-disable<ret>:powerline-enable<ret>`)

## Steps to reproduce

1. Create a minimal config file:
   ``` kakrc
   source "$val{config}/plugins/plug.kak/rc/plug.kak"

   plug "andreyorst/powerline.kak" defer powerline %{
       powerline-format 'git'
   } config %{
       powerline-start
   }
   ```
2. Open kakoune, execute `:plug-install<ret>`. Quit when powerline.kak is finished installing
3. `cd` to a git repository `cd ~/.config/kak/plugins/powerline.kak`
4. Open `kak` on a file in that repository `kak README.md` 

## What should happen

I expect there to be a powerline module with the name of the current branch (`master`) as well as a branch symbol.

## What happens instead

The status line is completely empty. If you run `:powerline-disable<ret>:powerline-enable<ret>`, the module properly loads/renders.

## Environment information
Kakoune version: c2516f02f6ec036647f65b10e80f556ab9a71aab
OS version: Ubuntu 20.04.1 LTS
`sh` executable version:
- `sh`: dash 0.5.10.2-6
- `bash` (default login shell): GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
`git` version: 2.25.1

**Comment by andreyorst** [comment]
Thank you for the issue, but unfortunately I currently have little time, and can't work on this plugin anymore. I'm currently looking for maintainers, so if you're interested, you can find more info here: https://discuss.kakoune.com/t/maintainance-warning-and-request

**Comment by johnisom** [comment]
Thanks for your reply. Best of luck with your new job

**Comment by andreyorst** [comment]
according to the merge request from @jdugan6240 this should now be fixed
