### ISSUE TITLE
Configuring without plug.kak

### ISSUE THREAD

**Issue by Pound-Hash** [andreyorst/powerline.kak#25]
## Problem description

The README doesn't explain how to configure it without `plug.kak`. I tried configuring it by setting an option with `set-option global powerline_format 'git bufname line_column mode_info filetype lsp'` in my `kakrc`, but it didn't work. I also tried using a `hook` with `powerline-start`, but I don't know what I'm doing there, and it doesn't work either.

**Comment by andreyorst** [comment]
Are there any errors in the `*debug*` buffer?
I guess, the problem is that the variable is undefined. You should require module that this variable is defined first, then set it, and after that call the `powerline-start`.

```kakscript
require-module powerline
set-option global powerline_format 'git bufname line_column mode_info filetype lsp' 
powerline-start
```

**Comment by Pound-Hash** [comment]
That works. Thanks!
