### ISSUE TITLE
The mode_info module doesn't display themed colors

### ISSUE THREAD

**Issue by Pound-Hash** [andreyorst/powerline.kak#27]
## Problem description
The `insert` and `select` are pulling their colors from my `kakrc`, not from the color definitions of any of powerline's themes.

![20220405_21h00m32s_grim](https://user-images.githubusercontent.com/51193876/161893734-b1095ed0-444c-4069-bc47-0faf66257ba1.png)

I tried removing the color definitions from my `kakrc`, but then `mode_info` just uses my default foreground from Kakoune (off-white).

### Config
```
### Powerline
    require-module powerline
    set-option global powerline_format 'git bufname filetype mode_info lsp'
    set-option global powerline_shorten_bufname name
    powerline-start
    hook global BufOpenFile .* expandtab
    hook global BufNewFile  .* expandtab
```

## Environment information
Kakoune version: v2021.11.08
OS version: Arch
`sh` executable version: zsh 5.8.1

**Comment by andreyorst** [comment]
I'm going to close this, as this isn't much I can do unless Kakoune will allow coloring these elements separately from the rest of UI
